name: kcwiulb
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - astropy
  - matplotlib
  - pyyaml
  - tqdm
  - shapely
  - bokeh
  - scikit-image   # <-- add this
  - pip
  - pip:
      - -e .
